services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

      - ./01-oltp-database/sql/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql:ro
      - ./01-oltp-database/sql/002_create_tables.sql:/docker-entrypoint-initdb.d/002_create_tables.sql:ro
      - ./01-oltp-database/sql/003_load_initial_data.sql:/docker-entrypoint-initdb.d/003_load_initial_data.sql:ro

      - ./01-oltp-database/data:/var/lib/mysql-files

  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./03-data-warehouse/sql:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
  postgres_data:
