services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: unless-stopped

    command: --local-infile=1

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./01-oltp-database/sql/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql:ro
      - ./01-oltp-database/sql/002_create_tables.sql:/docker-entrypoint-initdb.d/002_create_tables.sql:ro
      - ./01-oltp-database/data:/docker-entrypoint-data:ro

volumes:
  mysql_data:
